# The repositories hash is read automatically by buildr.
repositories:

  # customize user local maven2 repository location
  local: c:/Work/maven-repository

  # prefer the local or nearest mirrors
  remote: 
    - http://scriptlandia-repository.googlecode.com/svn/trunk/languages
    - http://scriptlandia-repository.googlecode.com/svn/trunk/tools
    - http://repository.springsource.com/maven/bundles/release
    - http://repository.springsource.com/maven/bundles/external
    - http://repository.springsource.com/maven/libraries/release
    - http://repository.springsource.com/maven/libraries/external
    - http://repository.jboss.com/maven2
    - http://repo.mergere.com/maven2
    - http://repo1.maven.org/maven2
    - http://repo1.maven.org/maven-spring
    - http://dist.codehaus.org
    - http://repository.codehaus.org
    - http://download.java.net/maven/2/
    - https://maven-repository.dev.java.net/nonav/repository
    - http://download.java.net/maven/2
    - http://jyaml.sourceforge.net/m2-repo
    - http://dist.codehaus.org/mule/dependencies/maven2

# The artifact declarations will be automatically loaded by buildr, so that
# you can reference artifacts by name (a ruby-symbol) on your buildfile.
artifacts:
  spring: org.springframework:spring:jar:2.0
  log4j: log4j:log4j:jar:1.0
  j2ee: geronimo-spec:geronimo-spec-j2ee:jar:1.4-rc4

options:
  proxy.http: 'http://10.226.67.31:8000'
