#
# Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Makefile for building Mozilla modules
#

BUILDDIR = ../..
PRODUCT = org
include $(BUILDDIR)/common/Defs.gmk

SUBDIRS =  mozilla
all build clean clobber::
	$(SUBDIRS-loop)

