#
# Copyright 2000-2005 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Makefile for building all of java
#

BUILDDIR = ../../..
PRODUCT = plugin
include $(BUILDDIR)/common/Defs.gmk

SUBDIRS = browser pack
all build clean clobber::
	$(SUBDIRS-loop)

