#
# Copyright 2005-2006 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Makefile for building packages under javax.xml
#

BUILDDIR = ../../..
PACKAGE = com.sun.xml
PRODUCT = xml
include $(BUILDDIR)/common/Defs.gmk

#
# Files to compile
#
AUTO_FILES_JAVA_DIRS = com/sun/activation \
		       org/relaxng/datatype

#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk
