# Rakefile for Scriptlandia-R

require 'rubygems'
require 'rake/gempackagetask'

spec = Gem::Specification.new do |s|
  s.name        = 'scriptlandia'
  s.autorequire = 'scriptlandia-r'
  s.version     = '0.0.1'
  s.author      = "Alexander Shvets"
  s.date        = %q{2008-11-02}
  s.description = 'Scriptlandia launcher.'
  s.email       = 'alexander.shvets@gmail.com'

  candidates = Dir.glob("{docs,lib,tests}/**/*")
  s.files = candidates.delete_if do |item|
    item.include?("svn") || item.include?("rdoc")
  end

  #s.has_rdoc = true
  #s.extra_rdoc_files = ["README"]
  #s.homepage = %q{http://www.rubyonrails.org}

  s.require_paths = ["lib"]
  s.requirements = ["none"]
  #s.rubyforge_project = %q{scriptlandia-r}
  s.rubygems_version = '1.3.0'
  #s.homepage = "http://www.joshost.com/MomLog"
  s.platform = Gem::Platform::RUBY
  #s.test_file = "tests/ts_momlog.rb"
  #s.add_dependency("BlueCloth", ">= 0.0.4")

  s.summary = %q{.}
end
 
Rake::GemPackageTask.new(spec) do |pkg| 
  pkg.need_tar = true 
end 
