# Rakefile for Scriptlandia-R

require 'rubygems'
require 'rake/gempackagetask'

spec = Gem::Specification.load('scriptlandia-r.gemspec')

Rake::GemPackageTask.new(spec) do |pkg| 
  pkg.need_tar = true 
end 
