#
# Copyright 1996-2007 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

BUILDDIR = ../../..
PACKAGE = sun.security.other
PRODUCT = sun
include $(BUILDDIR)/common/Defs.gmk

#
# Files
#
AUTO_FILES_JAVA_DIRS = \
    sun/security/acl \
    sun/security/ec \
    sun/security/jca \
    sun/security/pkcs \
    sun/security/pkcs12 \
    sun/security/provider \
    sun/security/rsa \
    sun/security/ssl \
    sun/security/timestamp \
    sun/security/validator \
    sun/security/x509 \
    com/sun/net/ssl/internal/ssl

#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk
