#
# Copyright 1999-2003 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Build the tnameserv executable.
#

BUILDDIR = ../../../../../../..
PACKAGE = com.sun.corba.se.impl.naming.cosnaming
PRODUCT = sun
include $(BUILDDIR)/common/Defs.gmk

#
# Files.
#
CORBA_JMK_DIRECTORY=$(TOPDIR)/make/com/sun/corba/minclude/
include $(CORBA_JMK_DIRECTORY)com_sun_corba_se_impl_naming_cosnaming.jmk
FILES_java = $(com_sun_corba_se_impl_naming_cosnaming_java)

#
# Rules.
#
include $(BUILDDIR)/common/Classes.gmk

