#
# Copyright 1997-2005 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Makefile for building all of java
#

BUILDDIR = ..
PRODUCT = org
include $(BUILDDIR)/common/Defs.gmk

SUBDIRS = ietf jcp

all build clean clobber::
	$(SUBDIRS-loop)
