#
# Copyright 1997-2005 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

BUILDDIR = ../../../../../..
PACKAGE = com.sun.corba.se.impl.activation
PRODUCT = Activation
include $(BUILDDIR)/common/Defs.gmk

SUBDIRS = orbd servertool
all build clean clobber::
	$(SUBDIRS-loop)

