#
# Copyright 2001-2005 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

# makefile for building  browser proxy service classes

BUILDDIR = ../../../../..
PACKAGE = com.sun.java.browser.net
PRODUCT = plugin
include $(BUILDDIR)/common/Defs.gmk

#
# Files
#
AUTO_FILES_JAVA_DIRS = com/sun/java/browser/net

#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk

