@ECHO OFF

SET CURRENT_DIR=%~dp0

SET DRIVE_LETTER=c:

set JAVA_HOME=%DRIVE_LETTER%/Java/jdk1.6.0

SET JLAUNCHPAD_VERSION=1.0.1

SET JLAUNCHPAD_PROJECT=%CURRENT_DIR%jlaunchpad-%JLAUNCHPAD_VERSION%

if not exist %JLAUNCHPAD_PROJECT% (
  %JAVA_HOME%/bin/jar xvf jlaunchpad-%JLAUNCHPAD_VERSION%-install.zip
)

cd %JLAUNCHPAD_PROJECT%

%JLAUNCHPAD_PROJECT%\installer.bat
