#
# Copyright 1998-2005 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

# makefile for building JPEG classes

BUILDDIR = ../../..
PACKAGE = com.sun.image.codec.jpeg
PRODUCT = sun
include $(BUILDDIR)/common/Defs.gmk

#
# Files
#
AUTO_FILES_JAVA_DIRS = com/sun/image/codec/jpeg

#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk

