#
# Copyright 1998-2007 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Makefile for building the Java 2D Demo
#

BUILDDIR = ../../..
PRODUCT = demo/jfc
DEMONAME = Java2Demo
include $(BUILDDIR)/common/Defs.gmk

DEMO_ROOT       = $(CLOSED_SRC)/share/demo/jfc/Java2D
DEMO_TOPFILES   = ./Java2Demo.html ./README.txt
DEMO_MAINCLASS  = java2d.Java2Demo
DEMO_DESTDIR    = $(DEMODIR)/jfc/Java2D

#
# Demo jar building rules.
#
include $(BUILDDIR)/common/Demo.gmk

