#
# Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Makefile for building packages under org.jcp
#

BUILDDIR = ../..
PACKAGE = org.jcp
PRODUCT = jcp
include $(BUILDDIR)/common/Defs.gmk

#
# Files to compile
#
AUTO_FILES_JAVA_DIRS = org/jcp

#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk
