#
# Copyright 1997-2006 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

BUILDDIR = ../..
PACKAGE = java.accessibility
PRODUCT = java
include $(BUILDDIR)/common/Defs.gmk

#
# Files
#
AUTO_FILES_JAVA_DIRS = javax/accessibility

#
# Resources
#
LOCALE_SUFFIXES += en
LOCALE_SET_DEFINITION = jre
RESOURCE_BUNDLES_COMPILED_PROPERTIES = \
      com/sun/accessibility/internal/resources/accessibility.properties

#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk

