#
# Copyright 2003-2005 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Makefile for building all of java
#

BUILDDIR = ../../../../../..
PRODUCT = legacy

include $(BUILDDIR)/common/Defs.gmk

SUBDIRS = connection interceptor
all build clean clobber::
	$(SUBDIRS-loop)

