#
# Copyright 1996-2005 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Makefile for building sun.rmi.registry.* and the "rmiregistry" command
#

BUILDDIR = ../../..
PACKAGE = sun.rmi.registry
PRODUCT = sun
include $(BUILDDIR)/common/Defs.gmk

#
# Files
#
AUTO_FILES_JAVA_DIRS = sun/rmi/registry

#
# Resources
#
LOCALE_SET_DEFINITION = jre
RESOURCE_BUNDLES_PROPERTIES = $(PKGDIR)/resources/rmiregistry.properties

#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk

