#
# Copyright 1998-2007 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Build applet demo.
#

BUILDDIR = ../../..
PRODUCT = demo/applets
DEMONAME = TicTacToe
include $(BUILDDIR)/common/Defs.gmk

DEMO_ROOT    = $(CLOSED_SRC)/share/demo/applets/$(DEMONAME)
DEMO_DESTDIR = $(DEMODIR)/applets/$(DEMONAME)

#
# Demo jar building rules.
#
include $(BUILDDIR)/common/Demo.gmk

