#
# Copyright 1997-2005 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Makefile for building java.beans.*
#

BUILDDIR = ../..
PACKAGE = java.beans
PRODUCT = java
include $(BUILDDIR)/common/Defs.gmk

#
# Files to compile.
#
AUTO_FILES_JAVA_DIRS = java/beans com/sun/beans

#
# Rules.
#
include $(BUILDDIR)/common/Classes.gmk
