#
# Copyright 2006 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Makefile for building the jconsole-plugin
#

BUILDDIR = ../../..
PRODUCT = demo/scripting
DEMONAME = jconsole-plugin
include $(BUILDDIR)/common/Defs.gmk

DEMO_ROOT       = $(SHARE_SRC)/demo/scripting/$(DEMONAME)
DEMO_TOPFILES   = ./README.txt ./build.xml
DEMO_SRCDIR     = $(DEMO_ROOT)/src
DEMO_DESTDIR    = $(DEMODIR)/scripting/$(DEMONAME)

#
# Demo jar building rules.
#
include $(BUILDDIR)/common/Demo.gmk

