#
# Copyright 2003-2005 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Makefile for building RMI SSL socket factories 
#

BUILDDIR = ../../..
PACKAGE = javax.rmi.ssl
PRODUCT = sun
include $(BUILDDIR)/common/Defs.gmk

#
# Files to compile
#
AUTO_FILES_JAVA_DIRS = javax/rmi/ssl

#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk

