#
# Copyright 2000-2005 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

BUILDDIR = ../../../../..
PACKAGE = com.sun.corba.se.PortableActivation
PRODUCT = org

include $(BUILDDIR)/common/Defs.gmk

#
# Files
#

include $(MINCLUDES)com_sun_corba_se_PortableActivationIDL.jmk

FILES_java=$(com_sun_corba_se_PortableActivationIDL_java)

#
# Include
#
include $(BUILDDIR)/common/Classes.gmk
