#
# Copyright 2005-2006 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

BUILDDIR = ../../..
PRODUCT = demo/management
DEMONAME = JTop
include $(BUILDDIR)/common/Defs.gmk

DEMO_ROOT       = $(SHARE_SRC)/demo/management/$(DEMONAME)
DEMO_TOPFILES   = ./README.txt
DEMO_MAINCLASS  = $(DEMONAME)
DEMO_DESTDIR    = $(DEMODIR)/management/$(DEMONAME)

#
# Demo jar building rules.
#
include $(BUILDDIR)/common/Demo.gmk

