#
# Copyright 2007 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

BUILDDIR = ../..
PACKAGE = sun.launcher
PRODUCT = sun
include $(BUILDDIR)/common/Defs.gmk

#
# Java source files
#
AUTO_FILES_JAVA_DIRS = sun/launcher

#
# Resources
#
LOCALE_SET_DEFINITION = jre
NEW_RESOURCE_BUNDLES_PROPERTIES = $(PKGDIR)/resources/launcher.properties

#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk

