#
# Copyright 1995-2005 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

BUILDDIR = ../..
PACKAGE = sun.misc
PRODUCT = sun
include $(BUILDDIR)/common/Defs.gmk

#
# Files
#
AUTO_FILES_JAVA_DIRS = sun/misc

#
# Resources
#
LOCALE_SET_DEFINITION = jre
RESOURCE_BUNDLES_JAVA= sun/misc/resources/Messages.java

#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk

