#
# Copyright 2003-2005 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Makefile for building SNMP MIB instrumentation
#

BUILDDIR = ../../..
PACKAGE = sun.management.snmp
PRODUCT = sun
include $(BUILDDIR)/common/Defs.gmk

#
# Files to compile
#
AUTO_FILES_JAVA_DIRS = sun/management/snmp

#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk

