#
# Copyright 2003-2005 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Makefile for building SNMP runtime support for
# Sun-specific JDK out of the box management support.
#

BUILDDIR = ../../../..
PACKAGE = com.sun.jmx.snmp
PRODUCT = sun
include $(BUILDDIR)/common/Defs.gmk

#
# Files to compile
#
AUTO_FILES_JAVA_DIRS = com/sun/jmx/snmp

#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk

