#
# Copyright 2004-2006 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Makefile for building the CodePointInputMethod
#

BUILDDIR = ../../..
PRODUCT = demo/jfc
DEMONAME = CodePointIM
include $(BUILDDIR)/common/Defs.gmk

DEMO_ROOT       = $(SHARE_SRC)/demo/jfc/$(DEMONAME)
DEMO_TOPFILES   =  ./README.html ./README_ja.html ./README_zh_CN.html  
DEMO_MAINCLASS  = $(DEMONAME)
DEMO_DESCRIPTOR = java.awt.im.spi.InputMethodDescriptor
DEMO_DESTDIR    = $(DEMODIR)/jfc/$(DEMONAME)

#
# Demo jar building rules.
#
include $(BUILDDIR)/common/Demo.gmk

