#
# Copyright 2000-2005 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Makefile for building com/sun
#

BUILDDIR = ../../../..
include $(BUILDDIR)/common/Defs.gmk

SUBDIRS = dns 
all build clean clobber::
	$(SUBDIRS-loop)

