#
# Copyright 1998-2005 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Makefile for building client expression parsing code.
#

BUILDDIR = ../..
PACKAGE = com.sun.tools.example.debug.expr
PRODUCT = jpda
include $(BUILDDIR)/common/Defs.gmk

# Packages of java sources to compiler
AUTO_FILES_JAVA_DIRS = com/sun/tools/example/debug/expr

#
# Rules.
#
include $(BUILDDIR)/common/Classes.gmk

