#
# Copyright 2000-2005 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Makefile for building JDBC API and JDBC RowSet
#

BUILDDIR = ../..
PACKAGE = javax.sql
PRODUCT = sun
include $(BUILDDIR)/common/Defs.gmk

#
# Files to compile.
#
AUTO_FILES_JAVA_DIRS = javax/sql

# 
# Resources
#
OTHER_PROPERTIES  = $(PKGDIR)/rowset/rowset.properties

#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk

