#
# Copyright 2004 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

BUILDDIR = ../..
PRODUCT = demo/jpda
DEMONAME = jpda
include $(BUILDDIR)/common/Defs.gmk

DEMO_ROOT       = $(SHARE_SRC)/classes
DEMO_PKGDIR     = com/sun/tools/example
DEMO_TOPFILES   = ./com/sun/tools/example/README
DEMO_DESTDIR    = $(DEMODIR)/jpda

#
# Demo jar building rules.
#
include $(BUILDDIR)/common/Demo.gmk

