#
# Copyright 2002-2005 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Makefile for building Java input methods
#

BUILDDIR = ../../..
PRODUCT = sun
include $(BUILDDIR)/common/Defs.gmk

SUBDIRS = indicim thaiim
all build clean clobber::
	$(SUBDIRS-loop)

