#
# Copyright 1999-2005 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Makefile for building JNDI COS Naming service provider
#

BUILDDIR = ../../../..
PACKAGE = com.sun.jndi.cosnaming
PRODUCT = sun
include $(BUILDDIR)/common/Defs.gmk

#
# Resources
#
OTHER_PROPERTIES  = $(PKGDIR)/jndiprovider.properties

#
# Files to compile
#
AUTO_FILES_JAVA_DIRS = com/sun/jndi/cosnaming com/sun/jndi/url

#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk

