#
# Copyright 1998-2005 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Makefile for building the tty (aka JDB) on JDI
#

BUILDDIR = ../..
PACKAGE = com.sun.tools.example.debug.tty
PRODUCT = jpda
PROGRAM = jdb
include $(BUILDDIR)/common/Defs.gmk

#
# Java Files to compile are found automatically.
#
AUTO_FILES_JAVA_DIRS = com/sun/tools/example/debug/tty

#
# Resources
#
LOCALE_SET_DEFINITION = jdk
RESOURCE_BUNDLES_JAVA = com/sun/tools/example/debug/tty/TTYResources.java

#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk

