#
# Copyright 1999-2003 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Build the Persistent CosNaming Classes
#

BUILDDIR = ../../../../../../..
PACKAGE = com.sun.corba.se.impl.naming.pcosnaming
PRODUCT = PCosNaming
include $(BUILDDIR)/common/Defs.gmk

#
# Files
#
CORBA_JMK_DIRECTORY=$(TOPDIR)/make/com/sun/corba/minclude/
include $(CORBA_JMK_DIRECTORY)com_sun_corba_se_impl_naming_pcosnaming.jmk

#
# Include
#
include $(BUILDDIR)/common/Classes.gmk
