#
# Copyright 1998-2007 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Makefile for building javax
#

BUILDDIR = ..
include $(BUILDDIR)/common/Defs.gmk

SUBDIRS = xa

all build clean clobber::
	$(SUBDIRS-loop)
