#
# Copyright 2000-2005 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

# makefile for building Common DOM classes

BUILDDIR = ../../../../..
PACKAGE = com.sun.java.browser.dom
PRODUCT = plugin
include $(BUILDDIR)/common/Defs.gmk

#
# Files
#
AUTO_FILES_JAVA_DIRS = com/sun/java/browser/dom

#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk

