#
# Copyright 1995-2005 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Makefile for appletviewer classes, wrappers, and resources.
#

BUILDDIR = ../..
PACKAGE = sun.applet
PRODUCT = sun
include $(BUILDDIR)/common/Defs.gmk

#
# Files to compile.
#
AUTO_FILES_JAVA_DIRS = sun/applet

#
# Resources
#
LOCALE_SET_DEFINITION = jre
RESOURCE_BUNDLES_JAVA = sun/applet/resources/MsgAppletViewer.java

#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk

