#
# Copyright 2003-2005 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Makefile for building apache implementations
#

BUILDDIR = ../../..
PRODUCT = org
include $(BUILDDIR)/common/Defs.gmk

SUBDIRS =  apache
all build clean clobber::
	$(SUBDIRS-loop)

