#
# Copyright 2000-2002 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

BUILDDIR = ../../../../..

PACKAGE = com.sun.corba.se.interceptor
PRODUCT = sun

include $(BUILDDIR)/common/Defs.gmk

#
# Files
#

include FILES_java.gmk

#
# Include
#
include $(BUILDDIR)/common/Classes.gmk
