#
# Copyright 1999-2005 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Makefile for building all of java
#

BUILDDIR = ../../..
PRODUCT = corba
include $(BUILDDIR)/common/Defs.gmk

SUBDIRS = se
all build clean clobber::
	$(SUBDIRS-loop)

