#
# Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Makefile for building Mozilla JavaScript modules
#

BUILDDIR = ../../..
PRODUCT = org
include $(BUILDDIR)/common/Defs.gmk

SUBDIRS = javascript
all build clean clobber::
	$(SUBDIRS-loop)

