rem config.bat

rem Constants
SET JAVA_SPECIFICATION_VERSION=1.5
SET LAUNCHER_VERSION=1.0
SET CLASSWORLDS_VERSION=1.1

rem Default values
SET DRIVE_LETTER=d:
SET PROXY_SERVER_HOST_NAME=
SET PROXY_SERVER_PORT=
SET JAVA_HOME=%DRIVE_LETTER%\Java\jdk1.5.0
SET LAUNCHER_HOME=%DRIVE_LETTER%\launcher
SET REPOSITORY_HOME=%DRIVE_LETTER%\maven-repository

rem Overwrites default values, if exists
if exist "%USERPROFILE%\jlaunchpad\config.bat" (
  @call "%USERPROFILE%\jlaunchpad\config.bat"
)

IF NOT EXIST %JAVA_HOME% (
  ECHO JDK cannot be found!
  pause
  exit
)

rem System properties
SET SYSTEM_PROPERTIES="-Dlauncher.home=%LAUNCHER_HOME%"
SET SYSTEM_PROPERTIES=%SYSTEM_PROPERTIES% "-Drepository.home=%REPOSITORY_HOME%"
SET SYSTEM_PROPERTIES=%SYSTEM_PROPERTIES% -Dlauncher.version=%LAUNCHER_VERSION%
SET SYSTEM_PROPERTIES=%SYSTEM_PROPERTIES% -Dclassworlds.version=%CLASSWORLDS_VERSION%
SET SYSTEM_PROPERTIES=%SYSTEM_PROPERTIES% -Djava.specification.version=%JAVA_SPECIFICATION_VERSION%

IF NOT "%PROXY_SERVER_HOST_NAME" == "" (
  SET SYSTEM_PROPERTIES=%SYSTEM_PROPERTIES% -DproxyHost=%PROXY_SERVER_HOST_NAME% -DproxyPort=%PROXY_SERVER_PORT%
)

