#
# Copyright 2005 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Makefile for building JDBC API and JDBC RowSet
#

BUILDDIR = ../../..
PACKAGE = com.sun.sql
PRODUCT = sun
include $(BUILDDIR)/common/Defs.gmk

#
# Files to compile.
#
AUTO_FILES_JAVA_DIRS = com/sun/sql

#
# Rules.
#
include $(BUILDDIR)/common/Classes.gmk
