#
# Copyright 2003-2005 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Makefile for building intrinsic.properties for Pack200
# Unfortunately this file needs to be on its own due
# to a collision of rules with Classes.gmk and Library.gmk

BUILDDIR = ../../../../..
PACKAGE = com.sun.java.util.jar.pack
PRODUCT = sun
include $(BUILDDIR)/common/Defs.gmk

OTHER_PROPERTIES  = $(PKGDIR)/intrinsic.properties

#
# Rules.
#
include $(BUILDDIR)/common/Classes.gmk

