#
# Copyright 2000-2002 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

BUILDDIR = ../../../..
PACKAGE = com.sun.security.auth
PRODUCT = sun
include $(BUILDDIR)/common/Defs.gmk

#
# Files
#
include FILES_java.gmk

#
# Resources
#
LOCALE_SET_DEFINITION = jre
RESOURCE_BUNDLES_JAVA = sun/security/util/AuthResources.java

#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk

