#
# Copyright 1995-2005 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Makefile for building sun.audio
#

BUILDDIR = ../..
PACKAGE = sun.audio
PRODUCT = sun
include $(BUILDDIR)/common/Defs.gmk

#
# Files to compile
#
AUTO_FILES_JAVA_DIRS = sun/audio

#
# Rules
#
include $(BUILDDIR)/common/Classes.gmk

