#
# Copyright 2004 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

BUILDDIR = ../../..
PRODUCT = demo/jvmti
DEMONAME = gctest
include $(BUILDDIR)/common/Defs.gmk

DEMO_ROOT       = $(SHARE_SRC)/demo/jvmti/$(DEMONAME)
DEMO_TOPFILES   = ./README.txt
DEMO_DESTDIR    = $(DEMODIR)/jvmti/$(DEMONAME)

DEMO_OBJECTS = agent_util.$(OBJECT_SUFFIX)

#
# Demo jar building rules.
#
include $(BUILDDIR)/common/Demo.gmk

