#
# Copyright 2003-2005 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

BUILDDIR = ../../../../../..
PRODUCT = se

include $(BUILDDIR)/common/Defs.gmk

SUBDIRS = namingutil cosnaming pcosnaming
all build clean clobber::
	$(SUBDIRS-loop)

