#
# Copyright 1998-2005 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Build HPI (Host Porting Interface) libraries
#

BUILDDIR = ../..
include $(BUILDDIR)/common/Defs.gmk

#
# Build specified the HPI implementations
#
SUBDIRS = $(HPIS)
all build clean clobber::
	$(SUBDIRS-loop)

