#
# Copyright 2003-2005 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

BUILDDIR = ../../../../../..
PRODUCT = impl

include $(BUILDDIR)/common/Defs.gmk

# order is important

SUBDIRS = poa toa
all build clean clobber::
	$(SUBDIRS-loop)

