#
# Copyright 1998-2002 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Build applet demo.
#

BUILDDIR = ../../..
PRODUCT = demo/applets
DEMONAME = Clock
include $(BUILDDIR)/common/Defs.gmk

DEMO_ROOT    = $(SHARE_SRC)/demo/applets/$(DEMONAME)
DEMO_DESTDIR = $(DEMODIR)/applets/$(DEMONAME)

#
# Demo jar building rules.
#
include $(BUILDDIR)/common/Demo.gmk

