#
# Copyright 1998-2002 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Makefile to build the FileChooser demo.
#

BUILDDIR = ../../..
PRODUCT = demo/jfc
DEMONAME = FileChooserDemo
include $(BUILDDIR)/common/Defs.gmk

DEMO_ROOT       = $(SHARE_SRC)/demo/jfc/$(DEMONAME)
DEMO_TOPFILES   = ./README.txt
DEMO_MAINCLASS  = $(DEMONAME)
DEMO_DESTDIR    = $(DEMODIR)/jfc/$(DEMONAME)

#
# Demo jar building rules.
#
include $(BUILDDIR)/common/Demo.gmk

