CREATE TABLE USER_TEST (
  USER_ID VARCHAR(40) NOT NULL,
  FIRST_NAME VARCHAR (40) NOT NULL,
  LAST_NAME VARCHAR (40) NOT NULL,
  EMAIL VARCHAR (40) NOT NULL,
  PASSWORD VARCHAR(40) NOT NULL,
  PRIMARY KEY (USER_ID)
);

