#
# Copyright 1999-2006 Sun Microsystems, Inc.  All rights reserved.
# SUN PROPRIETARY/CONFIDENTIAL. Use is subject to license terms.
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#
#

#
# Build Poller class demo.
#

BUILDDIR = ../../..
PRODUCT = demo/jni
DEMONAME = Poller
include $(BUILDDIR)/common/Defs.gmk

DEMO_ROOT       = $(PLATFORM_SRC)/demo/jni/$(DEMONAME)
DEMO_TOPFILES   = ./README.txt
DEMO_MAINCLASS  = Client
DEMO_NATIVECLASS= $(DEMONAME)
DEMO_DESTDIR    = $(DEMODIR)/jni/$(DEMONAME)

#
# Demo jar building rules.
#
include $(BUILDDIR)/common/Demo.gmk

